# Generated by Django 4.2.5 on 2023-10-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThirdPartyToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("token", models.TextField(max_length=1024)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
